document.addEventListener("contextmenu", function (e) { e.preventDefault() }, !1), document.onkeydown = function (e) { return 123 != (e = e || window.event).keyCode && (!e.ctrlKey || !e.shiftKey || 73 != e.keyCode) && void 0 }; 

const removeWhiteSpace = e => e.replace(/\s/g, ""), hasValue = e => "" !== removeWhiteSpace(e), isNum = e => !isNaN(Number(removeWhiteSpace(e))), isInt = e => (e = Number(removeWhiteSpace(e)), !!Number.isInteger(e)), isPositive = e => (e = Number(removeWhiteSpace(e))) >= 0, dateIsValid = e => { return !!moment(e, "DD.MM.YYYY").isValid() }, validateYear = e => e >= 1920 || (alert("Năm cần lớn hơn 1920"), !1), validateMonth = e => e >= 1 && e <= 12; let sapXepTang = (...e) => (e.sort((e, t) => e - t), e); 

document.getElementById("sortNumber").onclick = function () {
     let e = document.getElementById("inputNum1").value, t = document.getElementById("inputNum2").value, n = document.getElementById("inputNum3").value, a = document.getElementById("txtSortNumber"); 
     if (hasValue(e) && isNum(e) && isInt(e) && hasValue(t) && isNum(t) && isInt(t) && hasValue(n) && isNum(n) && isInt(n)) { let i = sapXepTang(Number(removeWhiteSpace(e)), Number(removeWhiteSpace(t)), Number(removeWhiteSpace(n))); 
    a.innerHTML = i.join(",") } else a.innerHTML = "", alert("Dữ liệu không hợp lệ") },document.getElementById("btnHello").onclick = function () { var e = document.getElementById("selUser").value, t = document.getElementById("txtHello"); 

t.innerHTML = "B" == e ? "Xin chào Bố!" : "M" == e ? "Xin chào Mẹ!" : "A" == e ? "Xin chào Anh Trai!" : "E" == e ? "Xin chào Em gái!" : "Xin chào Người lạ ơi!" }, document.getElementById("btnCount").onclick = function () { var e = document.getElementById("inputCount1").value, t = document.getElementById("inputCount2").value, n = document.getElementById("inputCount3").value, a = 0; hasValue(e) && isNum(e) && isInt(e) && hasValue(t) && isNum(t) && isInt(t) && hasValue(n) && isNum(n) && isInt(n) ? (Number(removeWhiteSpace(e)) % 2 == 0 && a++, Number(removeWhiteSpace(t)) % 2 == 0 && a++, Number(removeWhiteSpace(n)) % 2 == 0 && a++, document.getElementById("txtCount").innerHTML = "Có " + a + " số chẵn," + (3 - a) + " số lẻ") : (document.getElementById("txtCount").innerHTML = "", alert("Dữ liệu không hợp lệ")) }; 

let checkCanhTamGiac = (e, t, n) => e + t > n && e + n > t && t + n > e; 

document.getElementById("btnEdge").onclick = function () { var e = document.getElementById("inputEdge1").value, t = document.getElementById("inputEdge2").value, n = document.getElementById("inputEdge3").value, a = document.getElementById("txtEdge"); if (hasValue(e) && isNum(e) && isPositive(e) && hasValue(t) && isNum(t) && isPositive(t) && hasValue(n) && isNum(n) && isPositive(n) && checkCanhTamGiac(Number(e), Number(t), Number(n))) { var i = Math.sqrt(Math.pow(t, 2) + Math.pow(n, 2)), u = Math.sqrt(Math.pow(e, 2) + Math.pow(n, 2)), m = Math.sqrt(Math.pow(e, 2) + Math.pow(t, 2)); a.innerHTML = e == t && t == n ? "Hình tam giác đều" : e == t || t == n || e == n ? "Hình tam giác cân" : e == i || t == u || n == m ? "Hình tam giác vuông" : "Một loại tam giác khác" } else a.innerHTML = "", alert("Dữ liệu không hợp lệ") }, document.getElementById("btnTomorrow").onclick = function () { var e = document.getElementById("inputDay").value, t = document.getElementById("inputMonth").value, n = document.getElementById("inputYear").value, a = ""; 

let i = hasValue(e) && isNum(e) && isPositive(e) && isInt(e) && hasValue(t) && isNum(t) && isPositive(t) && isInt(t) && hasValue(n) && isNum(n) && isPositive(n) && isInt(n) && dateIsValid(`${e}.${t}.${n}`); 

(i &= validateYear(Number(n))) ? ((a = new Date(`${n}-${t}-${e}`)).setDate(a.getDate() + 1), document.getElementById("txtDate").innerHTML = a.toLocaleDateString("en-GB")) : (document.getElementById("txtDate").innerHTML = "", alert("Dữ liệu không hợp lệ")) }, document.getElementById("btnYesterday").onclick = function () { var e = document.getElementById("inputDay").value, t = document.getElementById("inputMonth").value, n = document.getElementById("inputYear").value, a = ""; let i = hasValue(e) && isNum(e) && isPositive(e) && isInt(e) && hasValue(t) && isNum(t) && isPositive(t) && isInt(t) && hasValue(n) && isNum(n) && isPositive(n) && isInt(n) && dateIsValid(`${e}.${t}.${n}`); 
(i &= validateYear(Number(n))) ? ((a = new Date(`${n}-${t}-${e}`)).setDate(a.getDate() - 1), document.getElementById("txtDate").innerHTML = a.toLocaleDateString("en-GB")) : (document.getElementById("txtDate").innerHTML = "", alert("Dữ liệu không hợp lệ")) }, document.getElementById("btnCalcDay").onclick = function () { var e = document.getElementById("inputMonth2").value, t = document.getElementById("inputYear2").value, n = !1, a = 0; let i = hasValue(e) && isNum(e) && isPositive(e) && isInt(e) && hasValue(t) && isNum(t) && isPositive(t) && isInt(t); 
if (i &= validateYear(Number(t)) && validateMonth(Number(e))) { switch (e = Number(e), ((t = Number(t)) % 4 == 0 && t % 100 != 0 || t % 400 == 0) && (n = !0), e) { case 1: case 3: case 5: case 7: case 8: case 10: case 12: a = 31; break; case 4: case 6: case 9: case 11: a = 30; break; case 2: a = n ? 29 : 28; break; default: a = 0 }document.getElementById("txtCalcDay").innerHTML = "Tháng " + e + " năm " + t + " có " + a + " ngày" } else document.getElementById("txtCalcDay").innerHTML = "", alert("Dữ liệu không hợp lệ") }, document.getElementById("btnReadInt").addEventListener("click", function () { var e = document.getElementById("inputReadInt").value, t = Math.floor(e / 100), n = Math.floor(e % 100 / 10), a = e % 100 % 10, i = "", u = "", m = "", l = ""; if (!(hasValue(e) && isNum(e) && isInt(e) && Number(e) > 99 && Number(e) < 1e3)) return document.getElementById("txtReadInt").innerHTML = "", void alert("Dữ liệu không hợp lệ"); switch (t) { case 1: i = "một trăm "; break; case 2: i = "hai trăm "; break; case 3: i = "ba trăm "; break; case 4: i = "bốn trăm "; break; case 5: i = "năm trăm "; break; case 6: i = "sáu trăm "; break; case 7: i = "bảy trăm "; break; case 8: i = "tám trăm "; break; case 9: i = "chín trăm "; break; default: alert("số hàng trăm không xác định được") }switch (n) { case 0: u = "lẻ "; break; case 1: u = "mười "; break; case 2: u = "hai mươi "; break; case 3: u = "ba mươi "; break; case 4: u = "bốn mươi "; break; case 5: u = "năm mươi "; break; case 6: u = "sáu mươi "; break; case 7: u = "bảy mươi "; break; case 8: u = "tám mươi "; break; case 9: u = "chín mươi "; break; default: alert("Số hàng chục không xác định được") }switch (a) { case 0: m = ""; break; case 1: m = "một"; break; case 2: m = "hai"; break; case 3: m = "ba"; break; case 4: m = "bốn"; break; case 5: m = "năm"; break; case 6: m = "sáu"; break; case 7: m = "bảy"; break; case 8: m = "tám"; break; case 9: m = "chín"; break; default: alert("Số hàng đơn vị không xác định được.") }0 == a && 0 == n && (u = ""), isPositive(e) || (l = "âm "), document.getElementById("txtReadInt").innerHTML = l + i + u + m }), 

document.getElementById("btnSearch").addEventListener("click", function () { var e = document.getElementById("inputName1").value, t = document.getElementById("inputX1").value, n = document.getElementById("inputY1").value, a = document.getElementById("inputName2").value, i = document.getElementById("inputX2").value, u = document.getElementById("inputY2").value, m = document.getElementById("inputName3").value, l = document.getElementById("inputX3").value, c = document.getElementById("inputY3").value, s = document.getElementById("inputX4").value, o = document.getElementById("inputY4").value; if (!(hasValue(e) && hasValue(a) && hasValue(m) && isPositive(t) && isPositive(i) && isPositive(l) && isPositive(s) && isPositive(n) && isPositive(u) && isPositive(c) && isPositive(o))) return document.getElementById("txtSearch").innerHTML = "", void alert("Dữ liệu không hợp lệ"); var r = Math.pow(s - t, 2) + Math.pow(o - n, 2), d = Math.sqrt(r); console.log(d); var h = Math.pow(s - i, 2) + Math.pow(o - u, 2), g = Math.sqrt(h); console.log(g); var v = Math.pow(s - l, 2) + Math.pow(o - c, 2), I = Math.sqrt(v); console.log(I); var b = ""; b = d > g && d > I ? e : g > d && g > I ? a : m, 

document.getElementById("txtSearch").innerHTML = "Sinh viên xa trường nhất: " + b });